server:
  port: 8080
  context-path: /taskflow

#mysql config
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/taskflowdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://106.15.193.6:3306/taskflowdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: taskflow
    password: 123456abc
mybatis:
#  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:com/czh/taskflow/orm/dao/mapper/**/*.xml
  
